# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 9i;0l6-4kr
      MYSQL_DATABASE: helpcheckDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 9i;0l6-4kr
    ports:
      - 3306:3306
    volumes:
      - ./mysql-db:/var/lib/mysql
    networks:
      - localnetwork

  helpcheckapi:
    image: helpcheck-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - db
    networks:
      - localnetwork

networks:
  localnetwork:
    driver: bridge

  