# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  helpcheckapi:
    image: helpcheck-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000

  